### ISSUE TITLE
Continue working on an Event-driven Platform Forus

### ISSUE THREAD

**Issue by martijndoornik** [teamforus/rd-ethereum-eventhub#1]
Today, after having discussions for over a week, we came to a semi-final conclusion:

Right now, the top priority is realising Kindpakket for Zuidhorn and potential other municipalities. For this reason, most of the communication and discussions about the product should be eliminated. For this reason, Valentin will continue working on the Kindpakket product in Zuidhorn, for most part alone. This will require some Ethereum and IPFS interactions. For this reason, @jastam will build an MVP for document storage and I will build an MVP for Ethereum transactions, both connecting via HTTP. This way, the new Kindpakket version will still contain these functionalities.

However, to comply with the SBIR as much as possible, @jastam and I will work on further developing the platform as much as possible, aiming for a working prototype in August this year. This will then be the Me-app Backend, as a first step towards the Platform Forus.

**Comment by jamalv** [comment]
This decision has been implemented and I think this issue can be closed 👍
